language: java

script:
  - export LD_LIBRARY_PATH="/home/travis/build/abstractj/kalium/libsodium-1.0.13/vendor/lib"
  - mvn clean install

env: JAVA_OPTS="-Djava.library.path=/home/travis/build/abstractj/kalium/libsodium-1.0.13/vendor/lib"

jdk:
 - openjdk8

after_success:
  - rm -rf libsodium-1.0.13*
